// generated by github.com/elastic/goelasticsearch/cmd/generator; DO NOT EDIT

package client

import (
	"net/http"

	"github.com/elastic/goelasticsearch/client/cat"
	"github.com/elastic/goelasticsearch/client/cluster"
	"github.com/elastic/goelasticsearch/client/indices"
	"github.com/elastic/goelasticsearch/client/ingest"
	"github.com/elastic/goelasticsearch/client/nodes"
	"github.com/elastic/goelasticsearch/client/remote"
	"github.com/elastic/goelasticsearch/client/snapshot"
	"github.com/elastic/goelasticsearch/client/tasks"
)

// Client is the transport client.
type Client struct {
	// Cat is the cat client.
	Cat *cat.Cat

	// Cluster is the cluster client.
	Cluster *cluster.Cluster

	// Indices is the indices client.
	Indices *indices.Indices

	// Ingest is the ingest client.
	Ingest *ingest.Ingest

	// Nodes is the nodes client.
	Nodes *nodes.Nodes

	// Remote is the remote client.
	Remote *remote.Remote

	// Snapshot is the snapshot client.
	Snapshot *snapshot.Snapshot

	// Tasks is the tasks client.
	Tasks *tasks.Tasks

	// client is the transport client.
	client *http.Client
}

// addClients adds the subclients.
func (c *Client) addClients() {
	c.Cat = cat.New(c.client)
	c.Cluster = cluster.New(c.client)
	c.Indices = indices.New(c.client)
	c.Ingest = ingest.New(c.client)
	c.Nodes = nodes.New(c.client)
	c.Remote = remote.New(c.client)
	c.Snapshot = snapshot.New(c.client)
	c.Tasks = tasks.New(c.client)
}
