// generated by github.com/elastic/goelasticsearch/cmd/generator; DO NOT EDIT

package client

import (
	"fmt"
	"net/http"
	"reflect"
	"runtime"
)

// Delete allows to delete a typed JSON document from a specific index based on its id. See http://www.elastic.co/guide/en/elasticsearch/reference/master/docs-delete.html for more info.
//
// id: the document ID.
//
// index: the name of the index.
//
// documentType: the type of the document.
//
// options: optional parameters. Supports the following functional options: WithParent, WithRefresh, WithRouting, WithTimeout, WithVersion, WithVersionType, WithWaitForActiveShards, see the Option type in this package for more info.
func (c *Client) Delete(id string, index string, documentType string, options ...Option) (*http.Response, error) {
	supportedOptions := map[string]struct{}{
		"WithParent":              struct{}{},
		"WithRefresh":             struct{}{},
		"WithRouting":             struct{}{},
		"WithTimeout":             struct{}{},
		"WithVersion":             struct{}{},
		"WithVersionType":         struct{}{},
		"WithWaitForActiveShards": struct{}{},
	}
	for _, option := range options {
		name := runtime.FuncForPC(reflect.ValueOf(option).Pointer()).Name()
		if _, ok := supportedOptions[name]; !ok {
			return nil, fmt.Errorf("unsupported option: %s", name)
		}
	}
	req := &http.Request{
		Method: "DELETE",
	}
	return c.client.Do(req)
}
