// generated by github.com/elastic/goelasticsearch/cmd/generator; DO NOT EDIT

package client

import (
	"fmt"
	"net/http"
	"reflect"
	"runtime"
)

// GetScript - the scripting module enables you to use scripts to evaluate custom expressions. See http://www.elastic.co/guide/en/elasticsearch/reference/master/modules-scripting.html for more info.
//
// id: script ID.
//
// lang: script language.
func (c *Client) GetScript(id string, lang string, options ...Option) (*http.Response, error) {
	supportedOptions := map[string]struct{}{}
	for _, option := range options {
		name := runtime.FuncForPC(reflect.ValueOf(option).Pointer()).Name()
		if _, ok := supportedOptions[name]; !ok {
			return nil, fmt.Errorf("unsupported option: %s", name)
		}
	}
	req := &http.Request{
		Method: "GET",
	}
	return c.client.Do(req)
}
