// generated by github.com/elastic/goelasticsearch/cmd/generator; DO NOT EDIT

package client

import (
	"fmt"
	"net/http"
	"reflect"
	"runtime"
)

// ReindexRethrottle - reindex does not attempt to set up the destination index. See https://www.elastic.co/guide/en/elasticsearch/reference/master/docs-reindex.html for more info.
//
// requestsPerSecond: the throttle to set on this request in floating sub-requests per second. -1 means set no throttle.
//
// options: optional parameters. Supports the following functional options: WithTaskID, see the Option type in this package for more info.
func (c *Client) ReindexRethrottle(requestsPerSecond int, options ...Option) (*http.Response, error) {
	supportedOptions := map[string]struct{}{
		"WithTaskID": struct{}{},
	}
	for _, option := range options {
		name := runtime.FuncForPC(reflect.ValueOf(option).Pointer()).Name()
		if _, ok := supportedOptions[name]; !ok {
			return nil, fmt.Errorf("unsupported option: %s", name)
		}
	}
	req := &http.Request{
		Method: "POST",
	}
	return c.client.Do(req)
}
