// Licensed to Elasticsearch B.V. under one or more contributor
// license agreements. See the NOTICE file distributed with
// this work for additional information regarding copyright
// ownership. Elasticsearch B.V. licenses this file to you under
// the Apache License, Version 2.0 (the "License"); you may
// not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//    http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

// Code generated from the elasticsearch-specification DO NOT EDIT.
// https://github.com/elastic/elasticsearch-specification/tree/eb2e22fb2ac404e676d19bcc7bb089647f029026

package types

import (
	"bytes"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"strconv"
)

// The reasoning detail with encrypted reasoning data that may be redacted or
// protected.
//
// https://github.com/elastic/elasticsearch-specification/blob/eb2e22fb2ac404e676d19bcc7bb089647f029026/specification/inference/_types/CommonTypes.ts#L424-L434
type EncryptedReasoningDetail struct {
	// Data The encrypted reasoning data generated by the model, which may be redacted or
	// protected based on the model's configuration and the nature of the reasoning
	// information.
	Data string `json:"data"`
	// Format The format of the reasoning detail.
	Format *string `json:"format,omitempty"`
	// Id The identifier of the reasoning detail.
	Id *string `json:"id,omitempty"`
	// Index The index of the reasoning detail, which indicates its position in the
	// sequence of reasoning details generated by the model.
	Index *int   `json:"index,omitempty"`
	Type  string `json:"type,omitempty"`
}

func (s *EncryptedReasoningDetail) UnmarshalJSON(data []byte) error {

	dec := json.NewDecoder(bytes.NewReader(data))

	for {
		t, err := dec.Token()
		if err != nil {
			if errors.Is(err, io.EOF) {
				break
			}
			return err
		}

		switch t {

		case "data":
			var tmp json.RawMessage
			if err := dec.Decode(&tmp); err != nil {
				return fmt.Errorf("%s | %w", "Data", err)
			}
			o := string(tmp[:])
			o, err = strconv.Unquote(o)
			if err != nil {
				o = string(tmp[:])
			}
			s.Data = o

		case "format":
			var tmp json.RawMessage
			if err := dec.Decode(&tmp); err != nil {
				return fmt.Errorf("%s | %w", "Format", err)
			}
			o := string(tmp[:])
			o, err = strconv.Unquote(o)
			if err != nil {
				o = string(tmp[:])
			}
			s.Format = &o

		case "id":
			var tmp json.RawMessage
			if err := dec.Decode(&tmp); err != nil {
				return fmt.Errorf("%s | %w", "Id", err)
			}
			o := string(tmp[:])
			o, err = strconv.Unquote(o)
			if err != nil {
				o = string(tmp[:])
			}
			s.Id = &o

		case "index":

			var tmp any
			dec.Decode(&tmp)
			switch v := tmp.(type) {
			case string:
				value, err := strconv.Atoi(v)
				if err != nil {
					return fmt.Errorf("%s | %w", "Index", err)
				}
				s.Index = &value
			case float64:
				f := int(v)
				s.Index = &f
			}

		case "type":
			if err := dec.Decode(&s.Type); err != nil {
				return fmt.Errorf("%s | %w", "Type", err)
			}

		}
	}
	return nil
}

// MarshalJSON override marshalling to include literal value
func (s EncryptedReasoningDetail) MarshalJSON() ([]byte, error) {
	type innerEncryptedReasoningDetail EncryptedReasoningDetail
	tmp := innerEncryptedReasoningDetail{
		Data:   s.Data,
		Format: s.Format,
		Id:     s.Id,
		Index:  s.Index,
		Type:   s.Type,
	}

	tmp.Type = "reasoning.encrypted"

	return json.Marshal(tmp)
}

// NewEncryptedReasoningDetail returns a EncryptedReasoningDetail.
func NewEncryptedReasoningDetail() *EncryptedReasoningDetail {
	r := &EncryptedReasoningDetail{}

	return r
}

type EncryptedReasoningDetailVariant interface {
	EncryptedReasoningDetailCaster() *EncryptedReasoningDetail
}

func (s *EncryptedReasoningDetail) EncryptedReasoningDetailCaster() *EncryptedReasoningDetail {
	return s
}

func (s *EncryptedReasoningDetail) ReasoningDetailCaster() *ReasoningDetail {
	if s == nil {
		return nil
	}
	o := ReasoningDetail(s)
	return &o
}
