// generated by github.com/elastic/goelasticsearch/cmd/generator; DO NOT EDIT

package indices

import (
	"fmt"
	"net/http"
	"reflect"
	"runtime"
)

// ExistsType - used to check if a type/types exists in an index/indices. See http://www.elastic.co/guide/en/elasticsearch/reference/master/indices-types-exists.html for more info.
//
// index: a comma-separated list of index names; use _all to check the types across all indices.
//
// documentType: a comma-separated list of document types to check.
//
// options: optional parameters. Supports the following functional options: WithAllowNoIndices, WithExpandWildcards, WithIgnoreUnavailable, WithLocal, see the Option type in this package for more info.
func (i *Indices) ExistsType(index []string, documentType []string, options ...Option) (*http.Response, error) {
	supportedOptions := map[string]struct{}{
		"WithAllowNoIndices":    struct{}{},
		"WithExpandWildcards":   struct{}{},
		"WithIgnoreUnavailable": struct{}{},
		"WithLocal":             struct{}{},
	}
	for _, option := range options {
		name := runtime.FuncForPC(reflect.ValueOf(option).Pointer()).Name()
		if _, ok := supportedOptions[name]; !ok {
			return nil, fmt.Errorf("unsupported option: %s", name)
		}
	}
	req := &http.Request{
		Method: "HEAD",
	}
	return i.client.Do(req)
}
