// generated by github.com/elastic/goelasticsearch/cmd/generator; DO NOT EDIT

package indices

import (
	"fmt"
	"net/http"
	"net/url"
)

// Forcemerge - the force merge API allows to force merging of one or more indices through an API. See http://www.elastic.co/guide/en/elasticsearch/reference/master/indices-forcemerge.html for more info.
//
// options: optional parameters. Supports the following functional options: WithAllowNoIndices, WithErrorTrace, WithExpandWildcards, WithFilterPath, WithFlush, WithHuman, WithIgnoreUnavailable, WithIndex, WithMaxNumSegments, WithOnlyExpungeDeletes, WithOperationThreading, WithPretty, WithSourceParam, WithWaitForMerge, see the Option type in this package for more info.
func (i *Indices) Forcemerge(options ...*Option) (*http.Response, error) {
	supportedOptions := map[string]struct{}{
		"WithAllowNoIndices":     struct{}{},
		"WithErrorTrace":         struct{}{},
		"WithExpandWildcards":    struct{}{},
		"WithFilterPath":         struct{}{},
		"WithFlush":              struct{}{},
		"WithHuman":              struct{}{},
		"WithIgnoreUnavailable":  struct{}{},
		"WithIndex":              struct{}{},
		"WithMaxNumSegments":     struct{}{},
		"WithOnlyExpungeDeletes": struct{}{},
		"WithOperationThreading": struct{}{},
		"WithPretty":             struct{}{},
		"WithSourceParam":        struct{}{},
		"WithWaitForMerge":       struct{}{},
	}
	req := &http.Request{
		URL: &url.URL{
			Scheme: i.transport.Scheme,
			Host:   i.transport.Host,
		},
		Method: "POST",
	}
	for _, option := range options {
		if _, ok := supportedOptions[option.name]; !ok {
			return nil, fmt.Errorf("unsupported option: %s", option.name)
		}
		option.apply(req)
	}
	return i.transport.Do(req)
}
