// generated by github.com/elastic/goelasticsearch/cmd/generator; DO NOT EDIT

package indices

import (
	"net/http"
)

// Indices is the indices client.
type Indices struct {
	// client is the transport client.
	client *http.Client
}

// New is the constructor for Indices.
func New(client *http.Client) *Indices {
	return &Indices{
		client: client,
	}
}
