// generated by github.com/elastic/goelasticsearch/cmd/generator; DO NOT EDIT

package indices

import (
	"fmt"
	"net/http"
	"reflect"
	"runtime"
)

// Segments - provide low level segments information that a Lucene index (shard level) is built with. See http://www.elastic.co/guide/en/elasticsearch/reference/master/indices-segments.html for more info.
//
// options: optional parameters. Supports the following functional options: WithAllowNoIndices, WithErrorTrace, WithExpandWildcards, WithFilterPath, WithHuman, WithIgnoreUnavailable, WithIndex, WithOperationThreading, WithPretty, WithSourceParam, WithVerbose, see the Option type in this package for more info.
func (i *Indices) Segments(options ...Option) (*http.Response, error) {
	supportedOptions := map[string]struct{}{
		"WithAllowNoIndices":     struct{}{},
		"WithErrorTrace":         struct{}{},
		"WithExpandWildcards":    struct{}{},
		"WithFilterPath":         struct{}{},
		"WithHuman":              struct{}{},
		"WithIgnoreUnavailable":  struct{}{},
		"WithIndex":              struct{}{},
		"WithOperationThreading": struct{}{},
		"WithPretty":             struct{}{},
		"WithSourceParam":        struct{}{},
		"WithVerbose":            struct{}{},
	}
	for _, option := range options {
		name := runtime.FuncForPC(reflect.ValueOf(option).Pointer()).Name()
		if _, ok := supportedOptions[name]; !ok {
			return nil, fmt.Errorf("unsupported option: %s", name)
		}
	}
	req := &http.Request{
		Method: "GET",
	}
	return i.client.Do(req)
}
