// generated by github.com/elastic/goelasticsearch/cmd/generator; DO NOT EDIT

package indices

import (
	"fmt"
	"net/http"
	"net/url"
)

// Upgrade - see http://www.elastic.co/guide/en/elasticsearch/reference/master/indices-upgrade.html for more info.
//
// options: optional parameters. Supports the following functional options: WithAllowNoIndices, WithErrorTrace, WithExpandWildcards, WithFilterPath, WithHuman, WithIgnoreUnavailable, WithIndex, WithOnlyAncientSegments, WithPretty, WithSourceParam, WithWaitForCompletion, see the Option type in this package for more info.
func (i *Indices) Upgrade(options ...*Option) (*http.Response, error) {
	supportedOptions := map[string]struct{}{
		"WithAllowNoIndices":      struct{}{},
		"WithErrorTrace":          struct{}{},
		"WithExpandWildcards":     struct{}{},
		"WithFilterPath":          struct{}{},
		"WithHuman":               struct{}{},
		"WithIgnoreUnavailable":   struct{}{},
		"WithIndex":               struct{}{},
		"WithOnlyAncientSegments": struct{}{},
		"WithPretty":              struct{}{},
		"WithSourceParam":         struct{}{},
		"WithWaitForCompletion":   struct{}{},
	}
	req := &http.Request{
		URL: &url.URL{
			Scheme: i.transport.Scheme,
			Host:   i.transport.Host,
		},
		Method: "POST",
	}
	for _, option := range options {
		if _, ok := supportedOptions[option.name]; !ok {
			return nil, fmt.Errorf("unsupported option: %s", option.name)
		}
		option.apply(req)
	}
	return i.transport.Do(req)
}
