version: '3.5'
services:
  search_api:
    container_name: 'xkcd-search'
    build: .
    restart: 'on-failure'
    ports:
      - '8000:8000'
    depends_on:
      - elasticsearch
    networks:
      - elastic
  elasticsearch:
    container_name: 'es01'
    image: 'docker.elastic.co/elasticsearch/elasticsearch:8.1-SNAPSHOT'
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - xpack.security.enabled=false
    ports:
      - '9200:9200'
    networks:
      - elastic
    volumes:
      - es01:/usr/share/elasticsearch/data

volumes:
  es01:
    driver: local

networks:
  elastic:
    driver: bridge