version: '3.5'
services:
  search_api:
    container_name: 'xkcd-search'
    build: .
    restart: 'on-failure'
    ports:
      - '8000:8000'
    depends_on:
      - elasticsearch
  elasticsearch:
    container_name: 'es01'
    image: 'bitnami/elasticsearch:7'
    ports:
      - '9200:9200'
