// generated by github.com/elastic/goelasticsearch/cmd/generator; DO NOT EDIT

package indices

import (
	"fmt"
	"net/http"
	"net/url"
)

// Analyze - performs the analysis process on a text and return the tokens breakdown of the text. See https://www.elastic.co/guide/en/elasticsearch/reference/5.x/indices-analyze.html for more info.
//
// options: optional parameters. Supports the following functional options: WithIndex, WithAnalyzer, WithAttributes, WithCharFilter, WithExplain, WithField, WithFilter, WithFormat, WithIndexParam, WithPreferLocal, WithText, WithTokenizer, WithBody, WithErrorTrace, WithFilterPath, WithHuman, WithPretty, WithSourceParam, see the Option type in this package for more info.
func (i *Indices) Analyze(options ...*Option) (*http.Response, error) {
	supportedOptions := map[string]struct{}{
		"WithIndex":       struct{}{},
		"WithAnalyzer":    struct{}{},
		"WithAttributes":  struct{}{},
		"WithCharFilter":  struct{}{},
		"WithExplain":     struct{}{},
		"WithField":       struct{}{},
		"WithFilter":      struct{}{},
		"WithFormat":      struct{}{},
		"WithIndexParam":  struct{}{},
		"WithPreferLocal": struct{}{},
		"WithText":        struct{}{},
		"WithTokenizer":   struct{}{},
		"WithBody":        struct{}{},
		"WithErrorTrace":  struct{}{},
		"WithFilterPath":  struct{}{},
		"WithHuman":       struct{}{},
		"WithPretty":      struct{}{},
		"WithSourceParam": struct{}{},
	}
	req := &http.Request{
		URL: &url.URL{
			Scheme: i.transport.URL.Scheme,
			Host:   i.transport.URL.Host,
		},
		Method: "GET",
	}
	for _, option := range options {
		if _, ok := supportedOptions[option.name]; !ok {
			return nil, fmt.Errorf("unsupported option: %s", option.name)
		}
		option.apply(req)
	}
	return i.transport.Do(req)
}
