// generated by github.com/elastic/goelasticsearch/cmd/generator; DO NOT EDIT

package indices

import (
	"fmt"
	"net/http"
	"net/url"
)

// Segments - provide low level segments information that a Lucene index (shard level) is built with. See https://www.elastic.co/guide/en/elasticsearch/reference/5.x/indices-segments.html for more info.
//
// options: optional parameters. Supports the following functional options: WithAllowNoIndices, WithErrorTrace, WithExpandWildcards, WithFilterPath, WithHuman, WithIgnoreUnavailable, WithIndex, WithOperationThreading, WithPretty, WithSourceParam, WithVerbose, see the Option type in this package for more info.
func (i *Indices) Segments(options ...*Option) (*http.Response, error) {
	supportedOptions := map[string]struct{}{
		"WithAllowNoIndices":     struct{}{},
		"WithErrorTrace":         struct{}{},
		"WithExpandWildcards":    struct{}{},
		"WithFilterPath":         struct{}{},
		"WithHuman":              struct{}{},
		"WithIgnoreUnavailable":  struct{}{},
		"WithIndex":              struct{}{},
		"WithOperationThreading": struct{}{},
		"WithPretty":             struct{}{},
		"WithSourceParam":        struct{}{},
		"WithVerbose":            struct{}{},
	}
	req := &http.Request{
		URL: &url.URL{
			Scheme: i.transport.Scheme,
			Host:   i.transport.Host,
		},
		Method: "GET",
	}
	for _, option := range options {
		if _, ok := supportedOptions[option.name]; !ok {
			return nil, fmt.Errorf("unsupported option: %s", option.name)
		}
		option.apply(req)
	}
	return i.transport.Do(req)
}
