// generated by github.com/elastic/goelasticsearch/cmd/generator; DO NOT EDIT

package ingest

import (
	"net/http"
)

// Ingest is the ingest client.
type Ingest struct {
	// client is the transport client.
	client *http.Client
}

// New is the constructor for Ingest.
func New(client *http.Client) *Ingest {
	return &Ingest{
		client: client,
	}
}
