// generated by github.com/elastic/go-elasticsearch/cmd/generator; DO NOT EDIT

package tasks

import (
	"fmt"
	"net/http"
	"net/url"

	"github.com/elastic/go-elasticsearch/transport"
)

// List - the task management API allows to retrieve information about the tasks currently executing on one or more nodes in the cluster. See https://www.elastic.co/guide/en/elasticsearch/reference/5.x/tasks.html for more info.
//
// options: optional parameters. Supports the following functional options: WithActions, WithDetailed, WithGroupBy, WithNodeID, WithParentNode, WithParentTask, WithWaitForCompletion, WithErrorTrace, WithFilterPath, WithHuman, WithPretty, WithSourceParam, see the Option type in this package for more info.
func (t *Tasks) List(options ...*Option) (*ListResponse, error) {
	req := &http.Request{
		URL: &url.URL{
			Scheme: t.transport.URL.Scheme,
			Host:   t.transport.URL.Host,
		},
		Method: "GET",
	}
	methodOptions := supportedOptions["List"]
	for _, option := range options {
		if _, ok := methodOptions[option.name]; !ok {
			return nil, fmt.Errorf("unsupported option: %s", option.name)
		}
		option.apply(req)
	}
	resp, err := t.transport.Do(req)
	return &ListResponse{resp}, err
}

// ListResponse is the response for List
type ListResponse struct {
	Response *http.Response
	// TODO: fill in structured response
}

func (r *ListResponse) DecodeBody() (map[string]interface{}, error) {
	return transport.DecodeResponseBody(r.Response)
}
