// Package tasks is the tasks API package.
package tasks

// generated by github.com/elastic/go-elasticsearch/cmd/generator; DO NOT EDIT

import (
	"github.com/elastic/go-elasticsearch/transport"
)

// Tasks is the tasks client.
type Tasks struct {
	// transport is the transport client.
	transport *transport.Transport
}

// New is the constructor for Tasks. Note that this is automatically invoked by the client.Client type.
func New(transport *transport.Transport) *Tasks {
	return &Tasks{

		transport: transport,
	}
}
