// generated by github.com/elastic/goelasticsearch/cmd/generator; DO NOT EDIT

package cluster

import (
	"fmt"
	"net/http"
	"net/url"
)

// Stats - the Cluster Stats API allows to retrieve statistics from a cluster wide perspective. See https://www.elastic.co/guide/en/elasticsearch/reference/5.x/cluster-stats.html for more info.
//
// options: optional parameters. Supports the following functional options: WithNodeID, WithFlatSettings, WithTimeout, WithErrorTrace, WithFilterPath, WithHuman, WithPretty, WithSourceParam, see the Option type in this package for more info.
func (c *Cluster) Stats(options ...*Option) (*http.Response, error) {
	supportedOptions := map[string]struct{}{
		"WithNodeID":       struct{}{},
		"WithFlatSettings": struct{}{},
		"WithTimeout":      struct{}{},
		"WithErrorTrace":   struct{}{},
		"WithFilterPath":   struct{}{},
		"WithHuman":        struct{}{},
		"WithPretty":       struct{}{},
		"WithSourceParam":  struct{}{},
	}
	req := &http.Request{
		URL: &url.URL{
			Scheme: c.transport.URL.Scheme,
			Host:   c.transport.URL.Host,
		},
		Method: "GET",
	}
	for _, option := range options {
		if _, ok := supportedOptions[option.name]; !ok {
			return nil, fmt.Errorf("unsupported option: %s", option.name)
		}
		option.apply(req)
	}
	return c.transport.Do(req)
}
