// generated by github.com/elastic/goelasticsearch/cmd/generator; DO NOT EDIT

package cat

import (
	"fmt"
	"net/http"
	"net/url"
)

// ThreadPool - see https://www.elastic.co/guide/en/elasticsearch/reference/5.x/cat-thread-pool.html for more info.
//
// options: optional parameters. Supports the following functional options: WithErrorTrace, WithFilterPath, WithFormat, WithH, WithHelp, WithHuman, WithLocal, WithMasterTimeout, WithPretty, WithS, WithSize, WithSourceParam, WithThreadPoolPatterns, WithV, see the Option type in this package for more info.
func (c *Cat) ThreadPool(options ...*Option) (*http.Response, error) {
	supportedOptions := map[string]struct{}{
		"WithErrorTrace":         struct{}{},
		"WithFilterPath":         struct{}{},
		"WithFormat":             struct{}{},
		"WithH":                  struct{}{},
		"WithHelp":               struct{}{},
		"WithHuman":              struct{}{},
		"WithLocal":              struct{}{},
		"WithMasterTimeout":      struct{}{},
		"WithPretty":             struct{}{},
		"WithS":                  struct{}{},
		"WithSize":               struct{}{},
		"WithSourceParam":        struct{}{},
		"WithThreadPoolPatterns": struct{}{},
		"WithV":                  struct{}{},
	}
	req := &http.Request{
		URL: &url.URL{
			Scheme: c.transport.Scheme,
			Host:   c.transport.Host,
		},
		Method: "GET",
	}
	for _, option := range options {
		if _, ok := supportedOptions[option.name]; !ok {
			return nil, fmt.Errorf("unsupported option: %s", option.name)
		}
		option.apply(req)
	}
	return c.transport.Do(req)
}
