// generated by github.com/elastic/goelasticsearch/cmd/generator; DO NOT EDIT

package snapshot

import (
	"net/http"
)

// Snapshot is the snapshot client.
type Snapshot struct {
	// client is the transport client.
	client *http.Client
}

// New is the constructor for Snapshot.
func New(client *http.Client) *Snapshot {
	return &Snapshot{
		client: client,
	}
}
