// Package nodes is the nodes API package.
package nodes

// generated by github.com/elastic/go-elasticsearch/cmd/generator; DO NOT EDIT

import (
	"github.com/elastic/go-elasticsearch/transport"
)

// Nodes is the nodes client.
type Nodes struct {
	// transport is the transport client.
	transport *transport.Transport
}

// New is the constructor for Nodes. Note that this is automatically invoked by the client.Client type.
func New(transport *transport.Transport) *Nodes {
	return &Nodes{

		transport: transport,
	}
}
