// generated by github.com/elastic/goelasticsearch/cmd/generator; DO NOT EDIT

package tasks

import (
	"fmt"
	"net/http"
	"reflect"
	"runtime"
)

// Cancel - the task management API allows to retrieve information about the tasks currently executing on one or more nodes in the cluster. See http://www.elastic.co/guide/en/elasticsearch/reference/master/tasks.html for more info.
//
// options: optional parameters. Supports the following functional options: WithTaskID, WithActions, WithNodeID, WithParentNode, WithParentTask, see the Option type in this package for more info.
func (t *Tasks) Cancel(options ...Option) (*http.Response, error) {
	supportedOptions := map[string]struct{}{
		"WithTaskID":     struct{}{},
		"WithActions":    struct{}{},
		"WithNodeID":     struct{}{},
		"WithParentNode": struct{}{},
		"WithParentTask": struct{}{},
	}
	for _, option := range options {
		name := runtime.FuncForPC(reflect.ValueOf(option).Pointer()).Name()
		if _, ok := supportedOptions[name]; !ok {
			return nil, fmt.Errorf("unsupported option: %s", name)
		}
	}
	req := &http.Request{
		Method: "POST",
	}
	return t.client.Do(req)
}
