// Package ingest is the ingest API package.
package ingest

// generated by github.com/elastic/goelasticsearch/cmd/generator; DO NOT EDIT

import (
	"github.com/elastic/goelasticsearch/transport"
)

// Ingest is the ingest client.
type Ingest struct {
	// transport is the transport client.
	transport *transport.Transport
}

// New is the constructor for Ingest.
func New(transport *transport.Transport) *Ingest {
	return &Ingest{

		transport: transport,
	}
}
