// generated by github.com/elastic/goelasticsearch/cmd/generator; DO NOT EDIT

package cat

import (
	"net/http"
)

// Cat is the cat client.
type Cat struct {
	// client is the transport client.
	client *http.Client
}

// New is the constructor for Cat.
func New(client *http.Client) *Cat {
	return &Cat{
		client: client,
	}
}
