[[overview]]
== Overview

This is the official Go client for {es}.

Full documentation is hosted at 
https://github.com/elastic/go-elasticsearch[GitHub]
and https://pkg.go.dev/github.com/elastic/go-elasticsearch[PkgGoDev]. This 
documentation provides only an overview of features.

[discrete]
=== Features

* One-to-one mapping with REST API.
* Generalized, pluggable architecture.
* Helpers for convenience.
* Rich set of examples.


[discrete]
=== Usage

[source,go]
------------------------------------
package main

import (
  "log"

  "github.com/elastic/go-elasticsearch/v7"
)

func main() {
  es, _ := elasticsearch.NewDefaultClient()
  log.Println(es.Info())
}
------------------------------------

[NOTE]
Please have a look at the collection of comprehensive examples in the repository
at https://github.com/elastic/go-elasticsearch/tree/master/_examples.


[discrete]
=== Resources

* https://github.com/elastic/go-elasticsearch[Source Code]
* https://godoc.org/github.com/elastic/go-elasticsearch[API Documentation]
* https://github.com/elastic/go-elasticsearch/tree/master/_examples[Examples and Recipes]


[discrete]
=== License

Copyright 2019 {es}.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
