// generated by github.com/elastic/go-elasticsearch/cmd/generator; DO NOT EDIT

package snapshot

import (
	"net/http"
	"time"
)

// Option is a non-required API option that gets applied to an HTTP request.
type Option struct {
	name  string
	apply func(r *http.Request)
}

// WithBody - the snapshot definition.
func WithBody(body map[string]interface{}) *Option {
	return &Option{
		name: "WithBody",
		apply: func(r *http.Request) {
		},
	}
}

// WithErrorTrace - include the stack trace of returned errors.
func WithErrorTrace(errorTrace bool) *Option {
	return &Option{
		name: "WithErrorTrace",
		apply: func(r *http.Request) {
		},
	}
}

// WithFilterPath - a comma-separated list of filters used to reduce the respone.
func WithFilterPath(filterPath []string) *Option {
	return &Option{
		name: "WithFilterPath",
		apply: func(r *http.Request) {
		},
	}
}

// WithHuman - return human readable values for statistics.
func WithHuman(human bool) *Option {
	return &Option{
		name: "WithHuman",
		apply: func(r *http.Request) {
		},
	}
}

// WithIgnoreUnavailable - whether to ignore unavailable snapshots, defaults to false which means a SnapshotMissingException is thrown.
func WithIgnoreUnavailable(ignoreUnavailable bool) *Option {
	return &Option{
		name: "WithIgnoreUnavailable",
		apply: func(r *http.Request) {
		},
	}
}

// WithLocal - return local information, do not retrieve the state from master node (default: false).
func WithLocal(local bool) *Option {
	return &Option{
		name: "WithLocal",
		apply: func(r *http.Request) {
		},
	}
}

// WithMasterTimeout - explicit operation timeout for connection to master node.
func WithMasterTimeout(masterTimeout time.Time) *Option {
	return &Option{
		name: "WithMasterTimeout",
		apply: func(r *http.Request) {
		},
	}
}

// WithPretty - pretty format the returned JSON response.
func WithPretty(pretty bool) *Option {
	return &Option{
		name: "WithPretty",
		apply: func(r *http.Request) {
		},
	}
}

// WithRepository - a comma-separated list of repository names.
func WithRepository(repository []string) *Option {
	return &Option{
		name: "WithRepository",
		apply: func(r *http.Request) {
		},
	}
}

// WithSourceParam - the URL-encoded request definition. Useful for libraries that do not accept a request body for non-POST requests.
func WithSourceParam(sourceParam string) *Option {
	return &Option{
		name: "WithSourceParam",
		apply: func(r *http.Request) {
		},
	}
}

// WithTimeout - explicit operation timeout.
func WithTimeout(timeout time.Time) *Option {
	return &Option{
		name: "WithTimeout",
		apply: func(r *http.Request) {
		},
	}
}

// WithVerify - whether to verify the repository after creation.
func WithVerify(verify bool) *Option {
	return &Option{
		name: "WithVerify",
		apply: func(r *http.Request) {
		},
	}
}

// WithWaitForCompletion - should this request wait until the operation has completed before returning.
func WithWaitForCompletion(waitForCompletion bool) *Option {
	return &Option{
		name: "WithWaitForCompletion",
		apply: func(r *http.Request) {
		},
	}
}

var (
	supportedOptions = map[string]map[string]struct{}{
		"Create": map[string]struct{}{
			"WithMasterTimeout":     struct{}{},
			"WithWaitForCompletion": struct{}{},
			"WithBody":              struct{}{},
			"WithErrorTrace":        struct{}{},
			"WithFilterPath":        struct{}{},
			"WithHuman":             struct{}{},
			"WithPretty":            struct{}{},
			"WithSourceParam":       struct{}{},
		},
		"CreateRepository": map[string]struct{}{
			"WithMasterTimeout": struct{}{},
			"WithTimeout":       struct{}{},
			"WithVerify":        struct{}{},
			"WithErrorTrace":    struct{}{},
			"WithFilterPath":    struct{}{},
			"WithHuman":         struct{}{},
			"WithPretty":        struct{}{},
			"WithSourceParam":   struct{}{},
		},
		"Delete": map[string]struct{}{
			"WithMasterTimeout": struct{}{},
			"WithErrorTrace":    struct{}{},
			"WithFilterPath":    struct{}{},
			"WithHuman":         struct{}{},
			"WithPretty":        struct{}{},
			"WithSourceParam":   struct{}{},
		},
		"DeleteRepository": map[string]struct{}{
			"WithMasterTimeout": struct{}{},
			"WithTimeout":       struct{}{},
			"WithErrorTrace":    struct{}{},
			"WithFilterPath":    struct{}{},
			"WithHuman":         struct{}{},
			"WithPretty":        struct{}{},
			"WithSourceParam":   struct{}{},
		},
		"Get": map[string]struct{}{
			"WithIgnoreUnavailable": struct{}{},
			"WithMasterTimeout":     struct{}{},
			"WithErrorTrace":        struct{}{},
			"WithFilterPath":        struct{}{},
			"WithHuman":             struct{}{},
			"WithPretty":            struct{}{},
			"WithSourceParam":       struct{}{},
		},
		"GetRepository": map[string]struct{}{
			"WithRepository":    struct{}{},
			"WithLocal":         struct{}{},
			"WithMasterTimeout": struct{}{},
			"WithErrorTrace":    struct{}{},
			"WithFilterPath":    struct{}{},
			"WithHuman":         struct{}{},
			"WithPretty":        struct{}{},
			"WithSourceParam":   struct{}{},
		},
		"Restore": map[string]struct{}{
			"WithMasterTimeout":     struct{}{},
			"WithWaitForCompletion": struct{}{},
			"WithBody":              struct{}{},
			"WithErrorTrace":        struct{}{},
			"WithFilterPath":        struct{}{},
			"WithHuman":             struct{}{},
			"WithPretty":            struct{}{},
			"WithSourceParam":       struct{}{},
		},
		"Status": map[string]struct{}{
			"WithRepository":        struct{}{},
			"WithSnapshot":          struct{}{},
			"WithIgnoreUnavailable": struct{}{},
			"WithMasterTimeout":     struct{}{},
			"WithErrorTrace":        struct{}{},
			"WithFilterPath":        struct{}{},
			"WithHuman":             struct{}{},
			"WithPretty":            struct{}{},
			"WithSourceParam":       struct{}{},
		},
		"VerifyRepository": map[string]struct{}{
			"WithMasterTimeout": struct{}{},
			"WithTimeout":       struct{}{},
			"WithErrorTrace":    struct{}{},
			"WithFilterPath":    struct{}{},
			"WithHuman":         struct{}{},
			"WithPretty":        struct{}{},
			"WithSourceParam":   struct{}{},
		},
	}
)
