// generated by github.com/elastic/goelasticsearch/cmd/generator; DO NOT EDIT

package cluster

import (
	"github.com/elastic/goelasticsearch/client/transport"
)

// Cluster is the cluster client.
type Cluster struct {
	// transport is the transport client.
	transport *transport.Transport
}

// New is the constructor for Cluster.
func New(transport *transport.Transport) *Cluster {
	return &Cluster{
		transport: transport,
	}
}
