// generated by github.com/elastic/goelasticsearch/cmd/generator; DO NOT EDIT

package cluster

import (
	"fmt"
	"net/http"
	"reflect"
	"runtime"
)

// Health - the cluster health API allows to get a very simple status on the health of the cluster. See http://www.elastic.co/guide/en/elasticsearch/reference/master/cluster-health.html for more info.
//
// options: optional parameters. Supports the following functional options: WithIndex, WithLevel, WithLocal, WithMasterTimeout, WithTimeout, WithWaitForActiveShards, WithWaitForEvents, WithWaitForNoRelocatingShards, WithWaitForNodes, WithWaitForStatus, see the Option type in this package for more info.
func (c *Cluster) Health(options ...Option) (*http.Response, error) {
	supportedOptions := map[string]struct{}{
		"WithIndex":                     struct{}{},
		"WithLevel":                     struct{}{},
		"WithLocal":                     struct{}{},
		"WithMasterTimeout":             struct{}{},
		"WithTimeout":                   struct{}{},
		"WithWaitForActiveShards":       struct{}{},
		"WithWaitForEvents":             struct{}{},
		"WithWaitForNoRelocatingShards": struct{}{},
		"WithWaitForNodes":              struct{}{},
		"WithWaitForStatus":             struct{}{},
	}
	for _, option := range options {
		name := runtime.FuncForPC(reflect.ValueOf(option).Pointer()).Name()
		if _, ok := supportedOptions[name]; !ok {
			return nil, fmt.Errorf("unsupported option: %s", name)
		}
	}
	req := &http.Request{
		Method: "GET",
	}
	return c.client.Do(req)
}
