// generated by github.com/elastic/goelasticsearch/cmd/generator; DO NOT EDIT

package cluster

import (
	"fmt"
	"net/http"
	"reflect"
	"runtime"
)

// PutSettings - allows to update cluster wide specific settings. See http://www.elastic.co/guide/en/elasticsearch/reference/master/cluster-update-settings.html for more info.
//
// body: the settings to be updated. Can be either transient or persistent (survives cluster restart).
//
// options: optional parameters. Supports the following functional options: WithFlatSettings, WithMasterTimeout, WithTimeout, see the Option type in this package for more info.
func (c *Cluster) PutSettings(body map[string]interface{}, options ...Option) (*http.Response, error) {
	supportedOptions := map[string]struct{}{
		"WithFlatSettings":  struct{}{},
		"WithMasterTimeout": struct{}{},
		"WithTimeout":       struct{}{},
	}
	for _, option := range options {
		name := runtime.FuncForPC(reflect.ValueOf(option).Pointer()).Name()
		if _, ok := supportedOptions[name]; !ok {
			return nil, fmt.Errorf("unsupported option: %s", name)
		}
	}
	req := &http.Request{
		Method: "PUT",
	}
	return c.client.Do(req)
}
