// generated by github.com/elastic/goelasticsearch/cmd/generator; DO NOT EDIT

package cluster

import (
	"fmt"
	"net/http"
	"reflect"
	"runtime"
)

// Stats - the Cluster Stats API allows to retrieve statistics from a cluster wide perspective. See http://www.elastic.co/guide/en/elasticsearch/reference/master/cluster-stats.html for more info.
//
// options: optional parameters. Supports the following functional options: WithErrorTrace, WithFilterPath, WithFlatSettings, WithHuman, WithNodeID, WithPretty, WithSourceParam, WithTimeout, see the Option type in this package for more info.
func (c *Cluster) Stats(options ...Option) (*http.Response, error) {
	supportedOptions := map[string]struct{}{
		"WithErrorTrace":   struct{}{},
		"WithFilterPath":   struct{}{},
		"WithFlatSettings": struct{}{},
		"WithHuman":        struct{}{},
		"WithNodeID":       struct{}{},
		"WithPretty":       struct{}{},
		"WithSourceParam":  struct{}{},
		"WithTimeout":      struct{}{},
	}
	for _, option := range options {
		name := runtime.FuncForPC(reflect.ValueOf(option).Pointer()).Name()
		if _, ok := supportedOptions[name]; !ok {
			return nil, fmt.Errorf("unsupported option: %s", name)
		}
	}
	req := &http.Request{
		Method: "GET",
	}
	return c.client.Do(req)
}
