// generated by github.com/elastic/goelasticsearch/cmd/generator; DO NOT EDIT

package cluster

import (
	"fmt"
	"net/http"
	"reflect"
	"runtime"
)

// State - the cluster state API allows to get a comprehensive state information of the whole cluster. See http://www.elastic.co/guide/en/elasticsearch/reference/master/cluster-state.html for more info.
//
// options: optional parameters. Supports the following functional options: WithIndex, WithMetric, WithAllowNoIndices, WithExpandWildcards, WithFlatSettings, WithIgnoreUnavailable, WithLocal, WithMasterTimeout, see the Option type in this package for more info.
func (c *Cluster) State(options ...Option) (*http.Response, error) {
	supportedOptions := map[string]struct{}{
		"WithIndex":             struct{}{},
		"WithMetric":            struct{}{},
		"WithAllowNoIndices":    struct{}{},
		"WithExpandWildcards":   struct{}{},
		"WithFlatSettings":      struct{}{},
		"WithIgnoreUnavailable": struct{}{},
		"WithLocal":             struct{}{},
		"WithMasterTimeout":     struct{}{},
	}
	for _, option := range options {
		name := runtime.FuncForPC(reflect.ValueOf(option).Pointer()).Name()
		if _, ok := supportedOptions[name]; !ok {
			return nil, fmt.Errorf("unsupported option: %s", name)
		}
	}
	req := &http.Request{
		Method: "GET",
	}
	return c.client.Do(req)
}
