// generated by github.com/elastic/goelasticsearch/cmd/generator; DO NOT EDIT

package remote

import (
	"github.com/elastic/goelasticsearch/client/transport"
)

// Remote is the remote client.
type Remote struct {
	// transport is the transport client.
	transport *transport.Transport
}

// New is the constructor for Remote.
func New(transport *transport.Transport) *Remote {
	return &Remote{
		transport: transport,
	}
}
