// generated by github.com/elastic/goelasticsearch/cmd/generator; DO NOT EDIT

package api

import (
	"fmt"
	"net/http"
	"net/url"
)

// UpdateByQuery - see https://www.elastic.co/guide/en/elasticsearch/reference/5.x/docs-update-by-query.html for more info.
//
// index: a comma-separated list of index names to search; use "_all" or empty string to perform the operation on all indices.
//
// options: optional parameters. Supports the following functional options: WithType, WithSource, WithSourceExclude, WithSourceInclude, WithAllowNoIndices, WithAnalyzeWildcard, WithAnalyzer, WithConflicts, WithDefaultOperator, WithDf, WithExpandWildcards, WithFrom, WithIgnoreUnavailable, WithLenient, WithPipeline, WithPreference, WithQ, WithRefresh, WithRequestCache, WithRequestsPerSecond, WithRouting, WithScroll, WithScrollSize, WithSearchTimeout, WithSearchType, WithSize, WithSlices, WithSort, WithStats, WithTerminateAfter, WithTimeout, WithVersion, WithVersionType, WithWaitForActiveShards, WithWaitForCompletion, WithBody, WithErrorTrace, WithFilterPath, WithHuman, WithPretty, WithSourceParam, see the Option type in this package for more info.
func (a *API) UpdateByQuery(index []string, options ...*Option) (*http.Response, error) {
	supportedOptions := map[string]struct{}{
		"WithType":                struct{}{},
		"WithSource":              struct{}{},
		"WithSourceExclude":       struct{}{},
		"WithSourceInclude":       struct{}{},
		"WithAllowNoIndices":      struct{}{},
		"WithAnalyzeWildcard":     struct{}{},
		"WithAnalyzer":            struct{}{},
		"WithConflicts":           struct{}{},
		"WithDefaultOperator":     struct{}{},
		"WithDf":                  struct{}{},
		"WithExpandWildcards":     struct{}{},
		"WithFrom":                struct{}{},
		"WithIgnoreUnavailable":   struct{}{},
		"WithLenient":             struct{}{},
		"WithPipeline":            struct{}{},
		"WithPreference":          struct{}{},
		"WithQ":                   struct{}{},
		"WithRefresh":             struct{}{},
		"WithRequestCache":        struct{}{},
		"WithRequestsPerSecond":   struct{}{},
		"WithRouting":             struct{}{},
		"WithScroll":              struct{}{},
		"WithScrollSize":          struct{}{},
		"WithSearchTimeout":       struct{}{},
		"WithSearchType":          struct{}{},
		"WithSize":                struct{}{},
		"WithSlices":              struct{}{},
		"WithSort":                struct{}{},
		"WithStats":               struct{}{},
		"WithTerminateAfter":      struct{}{},
		"WithTimeout":             struct{}{},
		"WithVersion":             struct{}{},
		"WithVersionType":         struct{}{},
		"WithWaitForActiveShards": struct{}{},
		"WithWaitForCompletion":   struct{}{},
		"WithBody":                struct{}{},
		"WithErrorTrace":          struct{}{},
		"WithFilterPath":          struct{}{},
		"WithHuman":               struct{}{},
		"WithPretty":              struct{}{},
		"WithSourceParam":         struct{}{},
	}
	req := &http.Request{
		URL: &url.URL{
			Scheme: a.transport.URL.Scheme,
			Host:   a.transport.URL.Host,
		},
		Method: "POST",
	}
	for _, option := range options {
		if _, ok := supportedOptions[option.name]; !ok {
			return nil, fmt.Errorf("unsupported option: %s", option.name)
		}
		option.apply(req)
	}
	return a.transport.Do(req)
}
