// generated by github.com/elastic/goelasticsearch/cmd/generator; DO NOT EDIT

package api

import (
	"fmt"
	"net/http"
	"net/url"
)

// Update allows to update a document based on a script provided. See https://www.elastic.co/guide/en/elasticsearch/reference/5.x/docs-update.html for more info.
//
// documentType: the type of the document.
//
// id: document ID.
//
// index: the name of the index.
//
// body: the request definition using either "script" or partial "doc".
//
// options: optional parameters. Supports the following functional options: WithErrorTrace, WithFields, WithFilterPath, WithHuman, WithLang, WithParent, WithPretty, WithRefresh, WithRetryOnConflict, WithRouting, WithSource, WithSourceExclude, WithSourceInclude, WithSourceParam, WithTimeout, WithTimestamp, WithTTL, WithVersion, WithVersionType, WithWaitForActiveShards, see the Option type in this package for more info.
func (a *API) Update(documentType string, id string, index string, body map[string]interface{}, options ...*Option) (*http.Response, error) {
	supportedOptions := map[string]struct{}{
		"WithErrorTrace":          struct{}{},
		"WithFields":              struct{}{},
		"WithFilterPath":          struct{}{},
		"WithHuman":               struct{}{},
		"WithLang":                struct{}{},
		"WithParent":              struct{}{},
		"WithPretty":              struct{}{},
		"WithRefresh":             struct{}{},
		"WithRetryOnConflict":     struct{}{},
		"WithRouting":             struct{}{},
		"WithSource":              struct{}{},
		"WithSourceExclude":       struct{}{},
		"WithSourceInclude":       struct{}{},
		"WithSourceParam":         struct{}{},
		"WithTimeout":             struct{}{},
		"WithTimestamp":           struct{}{},
		"WithTTL":                 struct{}{},
		"WithVersion":             struct{}{},
		"WithVersionType":         struct{}{},
		"WithWaitForActiveShards": struct{}{},
	}
	req := &http.Request{
		URL: &url.URL{
			Scheme: a.transport.URL.Scheme,
			Host:   a.transport.URL.Host,
		},
		Method: "POST",
	}
	for _, option := range options {
		if _, ok := supportedOptions[option.name]; !ok {
			return nil, fmt.Errorf("unsupported option: %s", option.name)
		}
		option.apply(req)
	}
	return a.transport.Do(req)
}
