// generated by github.com/elastic/go-elasticsearch/cmd/generator; DO NOT EDIT

package api

import (
	"fmt"
	"net/http"

	"github.com/elastic/go-elasticsearch/transport"
)

// Update allows to update a document based on a script provided. See https://www.elastic.co/guide/en/elasticsearch/reference/5.x/docs-update.html for more info.
//
// index: the name of the index.
//
// documentType: the type of the document.
//
// id: document ID.
//
// options: optional parameters. Supports the following functional options: WithSource, WithSourceExclude, WithSourceInclude, WithFields, WithLang, WithParent, WithRefresh, WithRetryOnConflict, WithRouting, WithTimeout, WithTimestamp, WithTTL, WithVersion, WithVersionType, WithWaitForActiveShards, WithBody, WithErrorTrace, WithFilterPath, WithHuman, WithIgnore, WithPretty, WithSourceParam, see the Option type in this package for more info.
func (a *API) Update(index string, documentType string, id string, options ...*Option) (*UpdateResponse, error) {
	req := a.transport.NewRequest("POST")
	methodOptions := supportedOptions["Update"]
	for _, option := range options {
		if _, ok := methodOptions[option.name]; !ok {
			return nil, fmt.Errorf("unsupported option: %s", option.name)
		}
		option.apply(req)
	}
	resp, err := a.transport.Do(req)
	return &UpdateResponse{resp}, err
}

// UpdateResponse is the response for Update.
type UpdateResponse struct {
	Response *http.Response
	// TODO: fill in structured response
}

// DecodeBody decodes the JSON body of the HTTP response.
func (r *UpdateResponse) DecodeBody() (map[string]interface{}, error) {
	return transport.DecodeResponseBody(r.Response)
}
